### ISSUE TITLE
Does this require a URL event listener?

### ISSUE THREAD

**Issue by seyDoggy** [jgarber623/RouterRouter#10]
I've followed your exact implementation and an not able to get RouterRouter to work on any path other than `'' : main`. It seems that there is nothing intercepting the URL events.

**Comment by BrockBeldham** [comment]
I'm having a similar problem. The root route is the only one that works. Example:

https://workspace-brockbeldham.c9.io/

When clicking the foo:bar link:
    <a href="/foo/1234">foo/:bar</a>

It just goes to a 404. I'm using the JS right from the example in the documentation.:

  (function () {
    var global = this;
    var RouterRouter = global.RouterRouter;

    var router = new RouterRouter({
        routes: {
            'foo/:bar': 'whiskey', // matches http://example.com/foo/1234
            'biz/*baz': 'tango',   // matches http://example.com/biz/1/2/3/4
            '': 'foxtrot'          // matches http://example.com/
        },
    
        foxtrot: function() {
            console.log('This very basic route matches the root URL.');
        },
    
        tango: function(baz) {
            console.log(baz); // logs 1/2/3/4
        },
    
        whiskey: function(bar) {
            console.log(bar); // logs 1234
        }
    });
}).call(this);

I did use Bower to install. Is it possible that the version in the Bower package is out of date?

**Comment by jgarber623** [comment]
@BrockBeldham In order for the function `whiskey` to fire, you would need a page [at this URL](https://workspace-brockbeldham.c9.io/foo/12345) which, as you've pointed out, does not exist.

RouterRouter fires functions by using the current page's URL and matching it against a series of patterns you define. As you're seeing, the root route is correctly firing on [your example page](https://workspace-brockbeldham.c9.io/).
