### ISSUE TITLE
README lack information

### ISSUE THREAD

**Issue by yairEO** [jgarber623/RouterRouter#13]
Does the code automatically detect window url change? (via interval) or do I need to trigger some function to manually check the current URL?

It's unclear how to work with this code on an SPA project. 

Thanks! looks promising though

**Comment by jgarber623** [comment]
From the [Limitations](https://github.com/jgarber623/RouterRouter#limitations) portion of the README:

> RouterRouter doesn't (currently) support the HTML5 History API. Support for this feature may be added in the future, but for now, keeping the library as small as possible remains the project's primary goal.

**Comment by yairEO** [comment]
who said anything about HTML 5 history? a person can write any URL and hit the enter key and I would expect a router to parse that url and break it down to splats and params, then I would decide which view to load according to the result. This has nothing to do with HTML5, it's more like HTML4 from the 90s.
